name: "CI"

on:
  push:
    branches: [main, beta]
  pull_request:
    branches: [main, beta]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: npm ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run release
